services:
  frontend:
    container_name: journo-frontend
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-/api}
        VITE_TURNSTILE_SITE_KEY: ${VITE_TURNSTILE_SITE_KEY:-1x00000000000000000000AA}
        VITE_ALLOWED_HOSTS: ${VITE_ALLOWED_HOSTS:-}
    env_file:
      - ./.env.frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped

  backend:
    container_name: journo-backend
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    env_file:
      - ./.env.supabase
    environment:
      GIN_MODE: release # Set debug for debug
      SERVER_PORT: 8080
    ports:
      - "8081:8080"
    restart: unless-stopped

